### ISSUE TITLE
Unable to execute solid init command

### ISSUE THREAD

**Issue by ranafaraz** [nodeSolidServer/node-solid-server#1739]
I am setting solid on a remote Linux-based server. Whenever I execute 'solid init' command, it generates this error: 

const Blob = globalThis.Blob || bufferModule.Blob
             ^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/ranaifwh/node/lib/node_modules/solid-server/node_modules/readable-stream/lib/ours/util.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ranaifwh/node/lib/node_modules/solid-server/node_modules/readable-stream/lib/stream.js:31:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)

Anybody can guide?

**Comment by bourgeoa** [comment]
You may look at https://github.com/solid/solidcommunity.net/wiki/solidcommunity.net-servers#solidcommunitynet-nss-instance

**Comment by melvincarvalho** [comment]
@ranafaraz what version of node?

**Comment by melvincarvalho** [comment]
Thank you for bringing this to our attention. It seems the issue was likely caused by using an older version of Node.js that doesn't support `globalThis`. 

Since this problem can be resolved by upgrading to a more recent version of Node.js (12.0.0 or later), and there haven't been any further reports, I suggest we close this issue.
